### ISSUE TITLE
This file is not a valid package

### ISSUE THREAD

**Issue by mariru27** [Caphyon/clang-power-tools#1040]
## When trying to install ClangPowerTools2022 after I changed id from extension.vsixmanifest and manifest.json
![image](https://user-images.githubusercontent.com/46792157/143406273-1bc9befe-5941-48d4-a1e3-ff7e82d0db48.png)

Install log

```
11/25/2021 10:27:26 AM - Microsoft VSIX Installer
11/25/2021 10:27:26 AM - -------------------------------------------
11/25/2021 10:27:26 AM - vsixinstaller.exe version:
11/25/2021 10:27:26 AM - 17.0.5226-preview5
11/25/2021 10:27:26 AM - -------------------------------------------
11/25/2021 10:27:26 AM - Command line parameters:
11/25/2021 10:27:26 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Marina Rusu\Desktop\Clang-Power-Tools\ClangPowerTools\CPTReleases\ClangPowerTools2022.vsix
11/25/2021 10:27:26 AM - -------------------------------------------
11/25/2021 10:27:26 AM - Microsoft VSIX Installer
11/25/2021 10:27:26 AM - -------------------------------------------
11/25/2021 10:27:27 AM - Initializing Install...
11/25/2021 10:27:27 AM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mariru27** [comment]
I fixed this.
The problem was in config,json, I modified ids there too.
