### ISSUE TITLE
Clang power tools crashes while analysing file

### ISSUE THREAD

**Issue by ronancor** [Caphyon/clang-power-tools#1129]
Hi, 

Clang power tool crashes visual studio when analysing one of my source files (it analysed a few others without issue). When I look in event log viewer I see the below log corresponding to the crash:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at ClangPowerTools.Output.OutputProcessor.GetOutputAndErrors(System.String, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.String ByRef, System.Collections.Generic.List`1<ClangPowerTools.TaskErrorModel> ByRef)
   at ClangPowerTools.Output.OutputProcessor.ProcessData(System.String, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, ClangPowerTools.Output.OutputContentModel)
   at ClangPowerTools.Output.OutputWindowController.OutputDataReceived(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by mariru27** [comment]
Hi @ronancor,

What command were you running when this crash occurred?
Is this issue reproducing on the same source file, running the same command?

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @ronancor,

Thank you for opening this issue and collaborating with us to find out what causes this crash.
We are working on fixing this bug

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @ronancor,

A release with bugfix for this issue is available in new [v2023.2.1 of Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help

Have a nice day,
Marina
