### ISSUE TITLE
Installer fails with two VS2017 Installations

### ISSUE THREAD

**Issue by TomSmartBishop** [Caphyon/clang-power-tools#139]
I have a second separate installation of VS2017 (only the build tools) and from the installer log I suspect that this second installation makes some troubles (I gave the second installation the nick name 'buildtool'):

`12/6/2017 3:33:30 PM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\v8.1\ExtensionSDKs\MSAdvertisingSdk\8.1\extension.vsixmanifest'
12/6/2017 3:33:30 PM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\v8.1\ExtensionSDKs\MSAdvertisingXaml\8.1\extension.vsixmanifest'
12/6/2017 3:33:30 PM - Found 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWSPHONEAPP\v8.1\ExtensionSDKs\Microsoft.Advertising.Mobile.Display\8.1\extension.vsixmanifest'
12/6/2017 3:33:30 PM - Skipping 'C:\Users\thpoll\AppData\Local\Microsoft SDKs' as it doesn't exist
12/6/2017 3:33:30 PM - The extension with ID 'Caphyon.705559db-5755-43fa-a023-41a3b14d2935' is not installed to Visual Studio Enterprise 2017.
12/6/2017 3:33:30 PM - Found installed product - Visual Studio Build Tools 2017 (buildtool)
12/6/2017 3:33:30 PM - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.TryGetProductVersion(String productVersionString, Version& productVersion)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.TryGetProductVersionFromPath(String path, Version& productVersion)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`

**Comment by Enache-Ionut** [comment]
Hi,

Can you tell us if the issue persisted on the new versions and if it still exists can you give us more information?

Thanks for your feedback.

**Comment by Enache-Ionut** [comment]
You can install the new version 2.5.1 just released today : https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools
