### ISSUE TITLE
Clang Power Tools 4.1 Crashes VS2017

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#435]
Unable to use the latest version (4.1) as it is crashing every time I try to use it, the previous version worked fine.
Please find below the details from the event log:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.VsShellUtilities.ShowMessageBox(System.IServiceProvider, System.String, System.String, Microsoft.VisualStudio.Shell.Interop.OLEMSGICON, Microsoft.VisualStudio.Shell.Interop.OLEMSGBUTTON, Microsoft.VisualStudio.Shell.Interop.OLEMSGDEFBUTTON)
   at ClangPowerTools.TidyCommand.<RunClangTidy>b__15_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ClangPowerTools.TidyCommand+<RunClangTidy>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by Enache-Ionut** [comment]
Hi,

Thank you for reporting this.
Can you please provide us more info about this issue: 
1. Can you send us your verbose mode output in case you can get it before this inconvenience to happen? Your settings are important for us.
2. It happens for every clang command or just happens for a particular one? 
3. Do you think you can attach a sample project reproducing the issue?

**Comment by netx123** [comment]
The issue was reproducible for me with VS 15.8.5, I have since upgraded to VS15.8.7 and that seems to have fixed the problem for now.

1) As it's now working in VS 15.8.7 I can no longer reproduce the issue so won't be able to create the verbose output that you need. (If the issue returns I will capture the verbose output for you)
2) The issue occurred using the "Compile" and "Tidy" options by right clicking a file, as well as when using the toolbar buttons for "Compile" and "Tidy" to check the entire project.
3) It was happening with all the projects I tried, so I don't believe it was project related.

**Comment by Enache-Ionut** [comment]
Thank you for your quick response. In this case I will close this issue for now, but please reopen it if the problem will occur again in the future.

Regards,
Ionut

**Comment by netx123** [comment]
OK ignore my last reply, as today its not working with VS15.8.7 either, so I'll try and create the verbose logs for you

**Comment by netx123** [comment]
I have enabled the Verbose Mode and reproduced the crash, but where can I find the verbose output?

**Comment by Enache-Ionut** [comment]
You will find the verbose log in the VS Output Window

**Comment by netx123** [comment]
But the crash is causing Visual Studio (devene.exe) to close immediately

**Comment by netx123** [comment]
After selecting any clang power tool option, I see the following error in the VS status bar:
"Unspecified error (Exception HRESULT: 0x80004005 (E_FAIL)) The tab has been closed."
Then VS crashes to desktop.

**Comment by netx123** [comment]
OK I have found the steps to reproduce the issue, if I attempt to launch Clang Power Tools before Visual Studio has finished parsing all the include folders during its first initialization I get the crash every time.
However if I wait until VS has fully finished its initialization (When it shows the "Ready" in the status bar), then Clang Power Tools works correctly.
It seems that the first launch of VS takes much longer to initialize than subsequent launches.
So here are the steps to reproduce: 
1) Reboot your computer, (this way VS will take much longer to initialize on its first launch after the reboot)
2) Launch Visual studio from desktop icon
3) In the recent project windows select a fairly large project
4) Now whilst VS is still showing that it is initializing/parsing etc in the status bar, quickly select a Clang Power Tool, Tidy or Compile option

**Comment by Enache-Ionut** [comment]
Thanks. We are currently working for a solution to solve this issue. We'll update this thread once the problem will be fixed. The fix for this issue it will be available in the next release v4.2.

**Comment by Enache-Ionut** [comment]
[Clang Power Tools v4.2](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) is now online. Please check for updates. I will wait for you to confirm the fix before to close this issue.

**Comment by netx123** [comment]
Hi, thanks for looking into the issue, unfortunately I've tested the latest update and it still causes the exact same crash.

**Comment by netx123** [comment]
I've compared the errors from 4.1 and 4.2 in the event log, the error generated by version 4.2 is slightly different I've highlighted the differences in bold below:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.VsShellUtilities.ShowMessageBox(System.IServiceProvider, System.String, System.String, Microsoft.VisualStudio.Shell.Interop.OLEMSGICON, Microsoft.VisualStudio.Shell.Interop.OLEMSGBUTTON, Microsoft.VisualStudio.Shell.Interop.OLEMSGDEFBUTTON)
   at ClangPowerTools.TidyCommand.**<RunClangTidy>**b__15_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ClangPowerTools.TidyCommand+**<RunClangTidy>**d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.**<ThrowAsync>**b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by Enache-Ionut** [comment]
Hi,

We have a possible fix for this issue even if we were not been able to reproduce this problem on our machines. Can you please check our solution before the official release? We want to be sure the next version will solve this inconvenience. It will be a great help for us.

We attached a `ZIP archive` which contains the `VSIX` file. To install the extension please follow the next steps:
1. First uninstall the old version
     1.1. Click on `Tools` -> `Extensions and Updates`
     1.2. Search in the `Installed` section for `Clang Power Tools`
     1.3. Click on `Uninstall`. Visual Studio must be closed during this process. 

2. Then install the new version
     2.1. Run `VSIX` file
     2.2. Check the wanted `Visual Studio version` and press `Install` button
     2.3. After the process is complete press `Close` button
     2.4. Run `Visual Studio`

[ClangPowerTools.zip](https://github.com/Caphyon/clang-power-tools/files/2486721/ClangPowerTools.zip)

**Comment by netx123** [comment]
Hi, I tested the VSIX update, but unfortunately it still has the same issue.
As I'm able to reproduce the issue here I've downloaded the source and will have a go at finding the cause.

**Comment by Enache-Ionut** [comment]
Thank you for your effort!  If you will try to reproduce the issue please check the next branch [fix-crash-on-first-command](https://github.com/Caphyon/clang-power-tools/tree/fix-crash-on-first-command). I fixed some small regressions from the previous version on it. You can try to work on this branch too.

**Comment by Enache-Ionut** [comment]
I integrated the branch mentioned above in master. I this way it will be more easy for you to get the fixes

**Comment by netx123** [comment]
I've spent a few days trying to identify the issue but I'm not really familiar enough with C# VS Extensions, so I haven't been able to make any progress.
I was however able to reproduce the issue in debug and got a more useful error message:

System.InvalidOperationException
  HResult=0x80131509
  Message=Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.

**Comment by Enache-Ionut** [comment]
Hi, We made several changes in order to fix this issue. If you can try our new VSIX :point_down: would be great. 

[ClangPowerTools.zip](https://github.com/Caphyon/clang-power-tools/files/2525693/ClangPowerTools.zip)

**Comment by netx123** [comment]
Followed the installation steps and I've tested with both the zip above, and the latest 2.4.1 release, but unfortunately the issue still remains.

**Comment by Enache-Ionut** [comment]
Hi,

We are have another VSIX for this issue 👇. We are waiting for your feedback.

[ClangPowerTools.zip](https://github.com/Caphyon/clang-power-tools/files/2552284/ClangPowerTools.zip)

**Comment by Enache-Ionut** [comment]
I'm glad to hear that. The new version containing this fix will be released today.
Thanks for your cooperation and feedback!
